package com.apigateway.common.enums;

public enum OperationType {
    CREATE,
    READ,
    UPDATE,
    DELETE,
    APPROVE,
    REJECT,
    ACTIVATE,
    DEACTIVATE,
    BATCH_ENABLE,
    BATCH_DISABLE,
    BATCH_SUBMIT_APPROVAL,
    BATCH_DELETE,
    GRAY_RELEASE_START,
    GRAY_RELEASE_FULL,
    GRAY_RELEASE_ROLLBACK,
    GRAY_RELEASE_PAUSE,
    GRAY_RELEASE_RESUME
}
